preguntas = {
    "Dragon Ball": [
            {"pregunta": "¿Quién es el creador de Dragon Ball?",
            "opciones": {"A": "Akira Toriyama", "B": "Masashi Kishimoto", "C": "Eiichiro Oda"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el planeta natal de Goku?",
            "opciones": {"A": "Planeta Vegeta", "B": "Namek", "C": "Planeta Tierra"},
            "respuesta": "A"},
            {"pregunta": "¿Quién fue el maestro de Goku en la saga original?",
            "opciones": {"A": "Maestro Roshi", "B": "Korin", "C": "Kami Sama"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el hermano de Goku?",
            "opciones": {"A": "Raditz", "B": "Vegeta", "C": "Nappa"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el nombre real de Goku?",
            "opciones": {"A": "Kakarotto", "B": "Son Goku", "C": "Bardock Jr."},
            "respuesta": "A"},
            {"pregunta": "¿Quién fue el primer villano que Goku enfrentó en Dragon Ball Z?",
            "opciones": {"A": "Raditz", "B": "Nappa", "C": "Freezer"},
            "respuesta": "A"},
            {"pregunta": "¿Qué técnica es enseñada por el Maestro Roshi?",
            "opciones": {"A": "Kamehameha", "B": "Genkidama", "C": "Kaioken"},
            "respuesta": "A"},
            {"pregunta": "¿Quién derrota a Cell en la saga de los Androides?",
            "opciones": {"A": "Gohan", "B": "Goku", "C": "Trunks"},
            "respuesta": "A"},
            {"pregunta": "¿Qué transformación desbloquea Goku por primera vez en Namek?",
            "opciones": {"A": "Super Saiyajin", "B": "Kaioken aumentado", "C": "Ultra Instinto"},
            "respuesta": "A"},
            {"pregunta": "¿Qué es Shenlong?",
            "opciones": {"A": "Un dragón que concede deseos", "B": "Un dios de la destrucción", "C": "Un saiyajin legendario"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el hijo mayor de Goku?",
            "opciones": {"A": "Trunks", "B": "Gohan", "C": "Goten"},
            "respuesta": "B"},
            {"pregunta": "¿Qué saga sigue después de la de Freezer?",
            "opciones": {"A": "Saga de Cell", "B": "Saga de los Androides", "C": "Saga de Majin Buu"},
            "respuesta": "B"},
            {"pregunta": "¿Cómo se llama el androide que protege a Goku y sus amigos?",
            "opciones": {"A": "Androide 17", "B": "Androide 16", "C": "Androide 18"},
            "respuesta": "B"},
            {"pregunta": "¿Quién entrena a Goku en el Otro Mundo?",
            "opciones": {"A": "Zeno sama", "B": "Kaio Sama", "C": "Kaio del sur"},
            "respuesta": "B"},
            {"pregunta": "¿Cómo se llama la forma fusionada de Goku y Vegeta con los pendientes Potara?",
            "opciones": {"A": "Gogeta", "B": "Vegito", "C": "Gotrunks"},
            "respuesta": "B"},
            {"pregunta": "¿Cuál es la transformación más poderosa de Goku en Dragon Ball Super?",
            "opciones": {"A": "Super Saiyajin Blue", "B": "Ultra Instinto", "C": "Super Saiyajin Dios"},
            "respuesta": "B"},
            {"pregunta": "¿Cómo se llama el villano que es un mago en Dragon Ball Z?",
            "opciones": {"A": "Dabura", "B": "Babidi", "C": "Majin Buu"},
            "respuesta": "B"},
            {"pregunta": "¿Quién fue el creador de los androides?",
            "opciones": {"A": "Doctor Myuu", "B": "Doctor Gero", "C": "Zamasu"},
            "respuesta": "B"},
            {"pregunta": "¿Qué saga sigue después del primer Torneo de las Artes Marciales de Goku?",
            "opciones": {"A": "Saga de Majin Buu", "B": "Saga del Ejército Red Ribbon", "C": "Saga de los Saiyajin"},
            "respuesta": "B"},
            {"pregunta": "¿Qué ataque usa Goku para derrotar a Kid Buu?",
            "opciones": {"A": "Kamehameha", "B": "Genkidama", "C": "Kaioken"},
            "respuesta": "B"},
            {"pregunta": "¿Qué se necesita para convocar a Shenlong?",
            "opciones": {"A": "Piedras mágicas", "B": "Entrenar en la Torre de Karin", "C": "Las siete Esferas del Dragón"},
            "respuesta": "C"},
            {"pregunta": "¿Cuál es el color del pelo del Super Saiyajin Dios?",
            "opciones": {"A": "Amarillo", "B": "Azul", "C": "Rojo"},
            "respuesta": "C"},
            {"pregunta": "¿Quién entrena a Gohan para enfrentarse a Cell?",
            "opciones": {"A": "Piccolo", "B": "Vegeta", "C": "Goku"},
            "respuesta": "C"},
            {"pregunta": "¿Quién es el hijo menor de Goku?",
            "opciones": {"A": "Gohan", "B": "Trunks", "C": "Goten"},
            "respuesta": "C"},
            {"pregunta": "¿Qué técnica usa Vegeta como su ataque característico?",
            "opciones": {"A": "Kamehameha", "B": "Genkidama", "C": "Final Flash"},
            "respuesta": "C"},
            {"pregunta": "¿Qué torneo reúne a luchadores de distintos universos?",
            "opciones": {"A": "Torneo Mundial", "B": "Torneo de Cell", "C": "Torneo del Poder"},
            "respuesta": "C"},
            {"pregunta": "¿Quién fue el primer amor de Bulma?",
            "opciones": {"A": "Krillin", "B": "Freezer", "C": "Yamcha"},
            "respuesta": "C"},
            {"pregunta": "¿Cómo se llama el planeta donde viven los Namekianos?",
            "opciones": {"A": "Planeta Vegeta", "B": "Planeta Tierra", "C": "Planeta Namek"},
            "respuesta": "C"},
            {"pregunta": "¿Quién es el creador de las Esferas del Dragón de la Tierra?",
            "opciones": {"A": "Los Namekianos", "B": "Maestro Roshi", "C": "Kami Sama"},
            "respuesta": "C"},
            {"pregunta": "¿Quién destruye al planeta Vegeta?",
            "opciones": {"A": "Goku", "B": "Raditz", "C": "Freezer"},
            "respuesta": "C"},
            {"pregunta": "¿Quién derrota a Freezer en Namek?",
            "opciones": {"A": "Goku", "B": "Gohan", "C": "Vegeta"},
            "respuesta": "A"},
            {"pregunta": "¿Qué arma usa Tao Pai Pai?",
            "opciones": {"A": "Una columna", "B": "Un bastón mágico", "C": "Una espada"},
            "respuesta": "A"},
            {"pregunta": "¿Qué objeto permite a Goku volar en Dragon Ball?",
            "opciones": {"A": "La nube voladora", "B": "La cápsula espacial", "C": "Un avión"},
            "respuesta": "A"},
            {"pregunta": "¿Qué relación tiene Bardock con Goku?",
            "opciones": {"A": "Es su padre", "B": "Es su hermano", "C": "Es su maestro"},
            "respuesta": "A"},
            {"pregunta": "¿Quién convierte a Vegeta en Majin Vegeta?",
            "opciones": {"A": "Babidi", "B": "Freezer", "C": "Dabura"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama la fusión de Goten y Trunks?",
            "opciones": {"A": "Gotenks", "B": "Gogeta", "C": "Vegito"},
            "respuesta": "A"},
            {"pregunta": "¿Qué objeto usa Bulma para buscar las esferas del dragón?",
            "opciones": {"A": "Radar dragón", "B": "Un telescopio", "C": "Un mapa"},
            "respuesta": "A"},
            {"pregunta": "¿Quién destruye la luna en Dragon Ball?",
            "opciones": {"A": "Piccolo", "B": "Gohan", "C": "Krillin"},
            "respuesta": "A"},
            {"pregunta": "¿Qué objeto puede revivir a una persona?",
            "opciones": {"A": "La nube voladora", "B": "Las esferas del dragón", "C": "El anillo de Kaio Shin"},
            "respuesta": "B"},
            {"pregunta": "¿Donde entreno Goku para poder usar el Kaioken?",
            "opciones": {"A": "En la Tierra", "B": "En el planeta del Kaio del Norte", "C": "En Namek"},
            "respuesta": "B"},
            {"pregunta": "¿Quién fue el villano principal de la saga de los Saiyajin?",
            "opciones": {"A": "Goku", "B": "Vegeta", "C": "Nappa"},
            "respuesta": "B"},
            {"pregunta": "¿Qué planeta fue destruido por Freezer?",
            "opciones": {"A": "Tierra", "B": "Planeta Vegeta", "C": "Planeta Namek"},
            "respuesta": "B"},
            {"pregunta": "¿Quién derrota a Dabura en Dragon Ball Z?",
            "opciones": {"A": "Gohan", "B": "Vegeta", "C": "Goku"},
            "respuesta": "B"},
            {"pregunta": "¿Quién usa el ataque 'Rayo de la Muerte'?",
            "opciones": {"A": "Piccolo", "B": "Freezer", "C": "Goku Black"},
            "respuesta": "B"},
            {"pregunta": "¿Qué objeto lleva el símbolo de la tortuga?",
            "opciones": {"A": "La nube voladora", "B": "El Gi de combate de Goku", "C": "El bastón mágico"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es el hijo de Vegeta?",
            "opciones": {"A": "Goten", "B": "Trunks", "C": "Gohan"},
            "respuesta": "B"},
            {"pregunta": "¿Qué ataque usa Piccolo como su especialidad?",
            "opciones": {"A": "Kamehameha", "B": "Makankosappo", "C": "Genkidama"},
            "respuesta": "B"},
    ]
}

def obtenerPreguntasDragonBall():
    return preguntas["Dragon Ball"]