preguntas = {
    "Naruto":[
            {"pregunta": "¿Quién fue el segundo Hokage?",
            "opciones": {"A": "Tobirama Senju", "B": "Hiruzen Sarutobi", "C": "Minato Namikaze"},
            "respuesta": "A"},
            {"pregunta": "¿Qué jutsu utiliza el clan Uchiha?",
            "opciones": {"A": "Rasengan", "B": "Amaterasu", "C": "Sharingan"},
            "respuesta": "C"},
            {"pregunta": "¿Quién es el primer líder presentado de los Akatsuki?",
            "opciones": {"A": "Madara Uchiha", "B": "Obito Uchiha", "C": "Pain"},
            "respuesta": "C"},
            {"pregunta": "¿Quién es el creador del Chidori?",
            "opciones": {"A": "Sasuke Uchiha", "B": "Obito Uchiha", "C": "Kakashi Hatake"},
            "respuesta": "C"},
            {"pregunta": "¿Qué tipo de jutsu usa Hinata?",
            "opciones": {"A": "Ninjutsu", "B": "Genjutsu", "C": "Dojutsu"},
            "respuesta": "C"},
            {"pregunta": "¿Qué característica tiene el Mangekyō Sharingan?",
            "opciones": {"A": "Rayo", "B": "Fuego", "C": "Illusión"},
            "respuesta": "C"},
            {"pregunta": "¿Quién fundó el clan Senju?",
            "opciones": {"A": "Tobirama Senju", "B": "Hashirama Senju", "C": "Naruto Uzumaki"},
            "respuesta": "B"},
            {"pregunta": "¿Quién tiene el jutsu Amaterasu?",
            "opciones": {"A": "Itachi Uchiha", "B": "Sasuke Uchiha", "C": "Tobi"},
            "respuesta": "A"},
            {"pregunta": "¿Quién es el creador del jutsu Rasengan?",
            "opciones": {"A": "Jiraiya", "B": "Kakashi Hatake", "C": "Minato Namikaze"},
            "respuesta": "C"},
            {"pregunta": "¿Qué ninja tiene el poder de controlar el fuego?",
            "opciones": {"A": "Naruto", "B": "Sasuke", "C": "Kakashi"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es considerado el antagonista principal de la serie?",
            "opciones": {"A": "Tobirama", "B": "Madara", "C": "Sasuke"},
            "respuesta": "B"},
            {"pregunta": "¿Qué biju está sellado en Gaara?",
            "opciones": {"A": "Nueve Colas", "B": "Shukaku", "C": "Isobu"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es el mejor amigo de Naruto?",
            "opciones": {"A": "Sasuke", "B": "Kakashi", "C": "Hinata"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el hermano de Sasuke?",
            "opciones": {"A": "Madara", "B": "Itachi", "C": "Obito"},
            "respuesta": "B"},
            {"pregunta": "¿Qué jutsu utiliza Sakura para sanar?",
            "opciones": {"A": "Rasengan", "B": "Chidori", "C": "Chakra de curación"},
            "respuesta": "C"},
            {"pregunta": "¿Quién es el principal enemigo en la Cuarta Gran Guerra Ninja?",
            "opciones": {"A": "Madara Uchiha", "B": "Obito Uchiha", "C": "Kabuto Yakushi"},
            "respuesta": "A"},
            {"pregunta": "¿Qué arma utiliza Sasuke en la batalla contra Naruto?",
            "opciones": {"A": "Rasengan", "B": "Chidori", "C": "Katana"},
            "respuesta": "C"},
            {"pregunta": "¿Cuál es la habilidad principal de Naruto?",
            "opciones": {"A": "Ninjutsu", "B": "Taijutsu", "C": "Genjutsu"},
            "respuesta": "A"},
            {"pregunta": "¿Qué clan tiene la habilidad de controlar las sombras?",
            "opciones": {"A": "Hyuga", "B": "Nara", "C": "Uchiha"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es el líder de la aldea de la Hoja?",
            "opciones": {"A": "Hiruzen Sarutobi", "B": "Minato Namikaze", "C": "Tobirama Senju"},
            "respuesta": "A"},
            {"pregunta": "¿Qué demonio está sellado dentro de Naruto?",
            "opciones": {"A": "Zorro de Nueve Colas", "B": "Cuervo", "C": "Jabalí"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el apellido de Sasuke?",
            "opciones": {"A": "Uchiha", "B": "Hyuga", "C": "Nara"},
            "respuesta": "A"},
            {"pregunta": "¿Qué es el Chidori?",
            "opciones": {"A": "Un jutsu de rayo", "B": "Un jutsu de fuego", "C": "Un jutsu de agua"},
            "respuesta": "A"},
            {"pregunta": "¿Quién fue el primer Hokage?",
            "opciones": {"A": "Hashirama Senju", "B": "Tobirama Senju", "C": "Hiruzen Sarutobi"},
            "respuesta": "A"},
            {"pregunta": "¿Qué es el Sharingan?",
            "opciones": {"A": "Un doujutsu", "B": "Un tipo de chakra", "C": "Una espada especial"},
            "respuesta": "A"},
            {"pregunta": "¿Quién es la novia de Naruto?",
            "opciones": {"A": "Sakura Haruno", "B": "Hinata Hyuga", "C": "Ino Yamanaka"},
            "respuesta": "B"},
            {"pregunta": "¿Qué habilidad tiene Rock Lee?",
            "opciones": {"A": "Taijutsu", "B": "Genjutsu", "C": "Ninjutsu"},
            "respuesta": "A"},
            {"pregunta": "¿Quién es el hermano de Sasuke?",
            "opciones": {"A": "Itachi Uchiha", "B": "Madara Uchiha", "C": "Obito Uchiha"},
            "respuesta": "A"},
            {"pregunta": "¿Qué significa el nombre de Naruto?",
            "opciones": {"A": "El viento", "B": "El sol", "C": "El remolino"},
            "respuesta": "C"},
            {"pregunta": "¿Qué tipo de ninja es Kakashi?",
            "opciones": {"A": "Ninja de tipo ninjutsu", "B": "Ninja de tipo genjutsu", "C": "Ninja de tipo taijutsu"},
            "respuesta": "A"},
            {"pregunta": "¿Qué jutsu utiliza Naruto para derrotar a sus enemigos?",
            "opciones": {"A": "Rasengan", "B": "Chidori", "C": "Amaterasu"},
            "respuesta": "A"},
            {"pregunta": "¿Qué clan tiene el Byakugan?",
            "opciones": {"A": "Hyuga", "B": "Uchiha", "C": "Nara"},
            "respuesta": "A"},
            {"pregunta": "¿Qué hace el jutsu de invocación de Naruto?",
            "opciones": {"A": "Invoca sapos", "B": "Invoca serpientes", "C": "Invoca aves"},
            "respuesta": "A"},
            {"pregunta": "¿Qué chakra tiene Sasuke después de su batalla con Naruto?",
            "opciones": {"A": "Chakra de fuego", "B": "Chakra de rayos", "C": "Chakra de hielo"},
            "respuesta": "B"},
            {"pregunta": "¿Quién entrenó a Sakura?",
            "opciones": {"A": "Kakashi Hatake", "B": "Tsunade Senju", "C": "Jiraiya"},
            "respuesta": "B"},
            {"pregunta": "¿Quién fue el maestro de Naruto?",
            "opciones": {"A": "Jiraiya", "B": "Tsunade", "C": "Kakashi"},
            "respuesta": "A"},
            {"pregunta": "¿Qué elemento controla Kakashi?",
            "opciones": {"A": "Rayo", "B": "Fuego", "C": "Agua"},
            "respuesta": "A"},
            {"pregunta": "¿Qué jinchuriki tiene la cola de una sola bestia?",
            "opciones": {"A": "Gaara", "B": "Naruto Uzumaki", "C": "Killer Bee"},
            "respuesta": "A"},
            {"pregunta": "¿Quién es el creador del jutsu Amaterasu?",
            "opciones": {"A": "Itachi Uchiha", "B": "Madara Uchiha", "C": "Obito Uchiha"},
            "respuesta": "A"},
            {"pregunta": "¿Qué posición ocupa Naruto en la aldea?",
            "opciones": {"A": "Hokage", "B": "Anbu", "C": "Chunin"},
            "respuesta": "A"},
            {"pregunta": "¿Quién tiene la habilidad de controlar la gravedad?",
            "opciones": {"A": "Sasuke Uchiha", "B": "Pain", "C": "Naruto Uzumaki"},
            "respuesta": "B"}
    ]
}

def obtenerPreguntasNaruto():
    return preguntas["Naruto"]