
preguntas = {
    "Yu-Gi-Oh!":[
        {"pregunta": "¿Quién es el protagonista principal de la serie original de Yu-Gi-Oh!?",
        "opciones": {"A": "Yugi Muto", "B": "Seto Kaiba", "C": "Joey Wheeler"},
        "respuesta": "A"},
        {"pregunta": "¿Qué carta emblemática representa a Yugi Muto?",
        "opciones": {"A": "Mago Oscuro", "B": "Dragón Blanco de Ojos Azules", "C": "Exodia el Prohibido"},
        "respuesta": "A"},
        {"pregunta": "¿Qué objeto del Milenio posee Yugi?",
        "opciones": {"A": "El Rompecabezas del Milenio", "B": "El Anillo del Milenio", "C": "El Ojo del Milenio"},
        "respuesta": "A"},
        {"pregunta": "¿Cuál es el poder del Rompecabezas del Milenio?",
        "opciones": {"A": "Conectar el alma de Yugi con el Faraón Atem", "B": "Controlar mentes", "C": "Ver el futuro"},
        "respuesta": "A"},
        {"pregunta": "¿Qué carta usa Kaiba como su favorita?",
        "opciones": {"A": "Dragón Blanco de Ojos Azules", "B": "Mago Oscuro", "C": "Cilindro Mágico"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llama el espíritu que habita en el Rompecabezas del Milenio?",
        "opciones": {"A": "Atem", "B": "Bakura", "C": "Marik"},
        "respuesta": "A"},
        {"pregunta": "¿Cuál es el tipo de monstruo principal en el mazo de Yugi?",
        "opciones": {"A": "Hechiceros", "B": "Dragones", "C": "Guerreros"},
        "respuesta": "A"},
        {"pregunta": "¿En qué torneo se enfrenta Yugi a Maximillion Pegasus?",
        "opciones": {"A": "Reino de los Duelistas", "B": "Batalla Ciudad", "C": "Gran Campeonato"},
        "respuesta": "A"},
        {"pregunta": "¿Quién es el dueño original del Dragón Alado de Ra?",
        "opciones": {"A": "Marik Ishtar", "B": "Yugi Muto", "C": "Seto Kaiba"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llaman las tres cartas de dioses egipcios?",
        "opciones": {"A": "Slifer, Obelisco y Ra", "B": "Ra, Anubis y Osiris", "C": "Horus, Set y Anubis"},
        "respuesta": "A"},
        {"pregunta": "¿Qué carta permite ganar automáticamente si se reúnen sus cinco partes?",
        "opciones": {"A": "Exodia el Prohibido", "B": "El Dragón Definitivo", "C": "El Soldado del Brillo Negro"},
        "respuesta": "A"},
        {"pregunta": "¿Cuál es el nombre del hermano menor de Seto Kaiba?",
        "opciones": {"A": "Mokuba Kaiba", "B": "Noah Kaiba", "C": "Marik Ishtar"},
        "respuesta": "A"},
        {"pregunta": "¿Qué forma de duelo introduce la serie GX?",
        "opciones": {"A": "Duelo en Disco", "B": "Duelo Sombra", "C": "Duelo Rápido"},
        "respuesta": "A"},
        {"pregunta": "¿Qué carta trampa utiliza Kaiba contra Pegasus?",
        "opciones": {"A": "Cilindro Mágico", "B": "Refuerza Ejército", "C": "Anillo de Destrucción"},
        "respuesta": "A"},
        {"pregunta": "¿Qué relación tiene Bakura con los objetos del Milenio?",
        "opciones": {"A": "Posee el Anillo del Milenio", "B": "Es el guardián del Rompecabezas", "C": "Busca destruirlos"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llama el creador del juego de cartas Duel Monsters?",
        "opciones": {"A": "Maximillion Pegasus", "B": "Seto Kaiba", "C": "Solomon Muto"},
        "respuesta": "A"},
        {"pregunta": "¿Qué carta es conocida por tener un ataque y defensa de 0 pero un poder especial?",
        "opciones": {"A": "Kuriboh", "B": "Cilindro Mágico", "C": "Sangan"},
        "respuesta": "A"},
        {"pregunta": "¿Qué carta invoca el Faraón Atem en el duelo final contra Yugi?",
        "opciones": {"A": "Slifer el Dragón del Cielo", "B": "Dragón Blanco de Ojos Azules", "C": "El Mago Oscuro"},
        "respuesta": "A"},
        {"pregunta": "¿Qué representa la Batalla Ciudad?",
        "opciones": {"A": "Un torneo organizado por Kaiba", "B": "Un enfrentamiento entre los mejores duelistas", "C": "La búsqueda de los Dioses Egipcios"},
        "respuesta": "A"},
        {"pregunta": "¿Qué relación tiene Solomon Muto con Yugi?",
        "opciones": {"A": "Es su abuelo", "B": "Es su tío", "C": "Es su maestro"},
        "respuesta": "A"},
        {"pregunta": "¿Qué carta es la contraparte del Mago Oscuro?",
        "opciones": {"A": "Dragón Blanco de Ojos Azules", "B": "Chica Maga Oscura", "C": "Buster Blader"},
        "respuesta": "B"},
        {"pregunta": "¿Qué tipo de cartas introdujo la serie Yu-Gi-Oh! 5D's?",
        "opciones": {"A": "Cartas de Fusión", "B": "Cartas de Sincronía", "C": "Cartas de Dioses"},
        "respuesta": "B"},
        {"pregunta": "¿Quién es el portador original del Ojo del Milenio?",
        "opciones": {"A": "Yugi Muto", "B": "Maximillion Pegasus", "C": "Bakura"},
        "respuesta": "B"},
        {"pregunta": "¿En qué duelo se enfrentan Kaiba y Joey?",
        "opciones": {"A": "Duelo preliminar en el Reino de los Duelistas", "B": "Semifinal de Batalla Ciudad", "C": "Duelo en el torneo KC"},
        "respuesta": "B"},
        {"pregunta": "¿Cuál es el tercer Dios Egipcio junto a Slifer y Ra?",
        "opciones": {"A": "Mago Oscuro", "B": "Obelisco el Atormentador", "C": "Dragón Alado del Sol"},
        "respuesta": "B"},
        {"pregunta": "¿Quién fue el primer villano principal de la serie original?",
        "opciones": {"A": "Marik Ishtar", "B": "Maximillion Pegasus", "C": "Bakura"},
        "respuesta": "B"},
        {"pregunta": "¿Qué tipo de monstruo suele usar Joey Wheeler?",
        "opciones": {"A": "Dragones", "B": "Guerreros", "C": "Hechiceros"},
        "respuesta": "B"},
        {"pregunta": "¿Qué carta entrega Solomon Muto a Yugi antes de Batalla Ciudad?",
        "opciones": {"A": "Exodia", "B": "Slifer el Dragón del Cielo", "C": "Dragón de Fusión Final"},
        "respuesta": "B"},
        {"pregunta": "¿Qué torneo organiza Kaiba después de Batalla Ciudad?",
        "opciones": {"A": "El Gran Campeonato", "B": "Torneo KC", "C": "El Reino de los Duelistas 2"},
        "respuesta": "B"},
        {"pregunta": "¿Qué carta de Joey es conocida por su capacidad para atacar directamente?",
        "opciones": {"A": "Dragón Negro de Ojos Rojos", "B": "Tiempo Mago", "C": "Pez Torpedo"},
        "respuesta": "B"},
        {"pregunta": "¿Qué vínculo tiene Marik Ishtar con los objetos del Milenio?",
        "opciones": {"A": "Es el portador del Ojo del Milenio", "B": "Busca destruirlos", "C": "No tiene vínculo"},
        "respuesta": "A"}
    ]
}



def obtenerPreguntasYugioh():
    return preguntas["Yu-Gi-Oh!"]