preguntas = {
    "Hunter X Hunter":[
            {"pregunta": "¿Cuál es el objetivo principal de Gon Freecss al inicio de la serie?",
            "opciones": {"A": "Encontrar a su padre", "B": "Hacer amigos", "C": "Explorar el mundo"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el mejor amigo de Killua?",
            "opciones": {"A": "Gon", "B": "Kurapika", "C": "Leorio"},
            "respuesta": "A"},
            {"pregunta": "¿Qué examen tiene que superar Gon para convertirse en cazador?",
            "opciones": {"A": "El Examen de Cazador", "B": "El Juego de Greed Island", "C": "El Torneo de Cazadores"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el arma característica de Kurapika?",
            "opciones": {"A": "Yoyos", "B": "Cadenas", "C": "Espadas"},
            "respuesta": "B"},
            {"pregunta": "¿Por qué es conocida la organización 'Genei Ryodan'?",
            "opciones": {"A": "Robar y causar caos", "B": "Proteger a los débiles", "C": "Buscar tesoros antiguos"},
            "respuesta": "A"},
            {"pregunta": "¿Qué acompaña a Gon en su búsqueda?",
            "opciones": {"A": "Su caña de pescar", "B": "Su perro", "C": "Su mascota Zushi"},
            "respuesta": "A"},
            {"pregunta": "¿Qué técnica utiliza Gon como su habilidad especial?",
            "opciones": {"A": "Jajanken", "B": "Nen Ball", "C": "Ren Fist"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el continente donde comienza la serie?",
            "opciones": {"A": "Continente Yorknew", "B": "Isla Ballena", "C": "Continente Oscuro"},
            "respuesta": "B"},
            {"pregunta": "¿Cuál es el alias de Chrollo Lucifer en la Genei Ryodan?",
            "opciones": {"A": "Ladrón de habilidades", "B": "Araña", "C": "Sombrío"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el tipo de Nen de Kurapika?",
            "opciones": {"A": "Conjuración", "B": "Emisor", "C": "Manipulador"},
            "respuesta": "A"},
            {"pregunta": "¿Qué relación tiene Silva Zoldyck con Killua?",
            "opciones": {"A": "Padre", "B": "Hermano", "C": "Tío"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el maestro de Nen de Gon y Killua?",
            "opciones": {"A": "Wing", "B": "Biscuit", "C": "Netero"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es el creador de Greed Island?",
            "opciones": {"A": "Ging Freecss", "B": "Netero", "C": "Chrollo Lucifer"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el poder principal de Hisoka?",
            "opciones": {"A": "Bungee Gum", "B": "Textura Engañosa", "C": "Volverse gelatina"},
            "respuesta": "A"},
            {"pregunta": "¿Qué exámenes enfrenta Gon además del Examen de Cazador?",
            "opciones": {"A": "Greed Island", "B": "Torneo de la Arena Celestial", "C": "Pruebas de la Genei Ryodan"},
            "respuesta": "B"},
            {"pregunta": "¿Qué habilidad usa Kurapika para vengarse del Genei Ryodan?",
            "opciones": {"A": "Cadenas", "B": "Espadas", "C": "Nen Oscuro"},
            "respuesta": "A"},
            {"pregunta": "¿Qué quiere conseguir Leorio al convertirse en cazador?",
            "opciones": {"A": "Dinero", "B": "Fama", "C": "Venganza"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el hermano mayor de Killua?",
            "opciones": {"A": "Illumi", "B": "Milluki", "C": "Kalluto"},
            "respuesta": "A"},
            {"pregunta": "¿Quién es el líder de la Asociación de Cazadores?",
            "opciones": {"A": "Isaac Netero", "B": "Pariston Hill", "C": "Ging Freecss"},
            "respuesta": "A"},
            {"pregunta": "¿Qué busca Kurapika a lo largo de la serie?",
            "opciones": {"A": "Venganza por su clan", "B": "Un artefacto antiguo", "C": "Salvar a Gon"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el objetivo principal de Gon Freecss?",
            "opciones": {"A": "Convertirse en un gran cazador", "B": "Buscar a su padre", "C": "Vengarse de Hisoka"},
            "respuesta": "B"},
            {"pregunta": "¿Cómo se llama la habilidad especial de Kurapika?",
            "opciones": {"A": "Ren", "B": "Ojo de kurta", "C": "Hatsu"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es el líder de la Tropa Fantasma?",
            "opciones": {"A": "Hisoka", "B": "Chrollo Lucilfer", "C": "Meruem"},
            "respuesta": "B"},
            {"pregunta": "¿Cuál es el poder de Nen de Gon?",
            "opciones": {"A": "Manipulación", "B": "Emisión", "C": "Reflexión"},
            "respuesta": "B"},
            {"pregunta": "¿Cuál es el apodo de Killua Zoldyck durante el examen de cazador?",
            "opciones": {"A": "El Niño Genio", "B": "El Asesino", "C": "El Rey del Dolor"},
            "respuesta": "B"},
            {"pregunta": "¿Qué elemento de poder utiliza Leorio en su técnica Nen?",
            "opciones": {"A": "Refuerzo", "B": "Emisión", "C": "Manipulación"},
            "respuesta": "A"},
            {"pregunta": "¿Qué poder tiene Meruem, el rey de las hormigas quimera?",
            "opciones": {"A": "Inmunidad al Nen", "B": "Control absoluto de los Nen", "C": "Inmunidad a la electricidad"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es el encargado de entrenar a Gon durante el principio de la serie?",
            "opciones": {"A": "Mito", "B": "Biscuit Krueger", "C": "Hisoka"},
            "respuesta": "A"},
            {"pregunta": "¿Qué tipo de Nen utiliza Hisoka?",
            "opciones": {"A": "Refuerzo", "B": "Transformación", "C": "Emisión"},
            "respuesta": "B"},
            {"pregunta": "¿Cuál es el nombre del grupo de cazadores que Gon forma en el examen?",
            "opciones": {"A": "Cazadores del Zodiaco", "B": "Compañeros de la Caza", "C": "Cazadores del Mundo"},
            "respuesta": "B"},
            {"pregunta": "¿Qué tipo de relación tiene Gon con su padre?",
            "opciones": {"A": "Paternal", "B": "Desconocida", "C": "Hostil"},
            "respuesta": "B"},
            {"pregunta": "¿Qué objeto importante Gon busca en el arco de la Isla Ballena?",
            "opciones": {"A": "Un mapa", "B": "La piedra de Zodiaco", "C": "La carta del poder"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el objetivo de los exámenes de cazador?",
            "opciones": {"A": "Conseguir el poder de un líder", "B": "Obtener la licencia de cazador", "C": "Alcanzar la independencia"},
            "respuesta": "B"},
            {"pregunta": "¿Qué habilidad tiene Killua Zoldyck cuando utiliza su Nen?",
            "opciones": {"A": "Electrocutar", "B": "Moverse a alta velocidad", "C": "Cargar energía en su cuerpo"},
            "respuesta": "A"},
            {"pregunta": "¿Cómo se llama el lugar donde Kurapika realiza el entrenamiento de Nen?",
            "opciones": {"A": "Mundo de los Nen", "B": "Torres de la Caza", "C": "Roca de los Elementos"},
            "respuesta": "B"},
            {"pregunta": "¿Qué organización es una de las principales antagonistas de la serie?",
            "opciones": {"A": "El Zodiaco", "B": "La Tropa Fantasma", "C": "Los Irregulars"},
            "respuesta": "B"},
            {"pregunta": "¿Quién es el protagonista principal de Hunter x Hunter?",
            "opciones": {"A": "Kurapika", "B": "Killua", "C": "Gon"},
            "respuesta": "C"},
            {"pregunta": "¿Qué habilidad especial usa Gon para invocar su Nen?",
            "opciones": {"A": "Hatsu", "B": "Ren", "C": "Gyo"},
            "respuesta": "A"},
            {"pregunta": "¿Cuál es el apellido de Killua?",
            "opciones": {"A": "Yamada", "B": "Kuzan", "C": "Zoldyck"},
            "respuesta": "C"},
            {"pregunta": "¿Qué nombre recibe la habilidad de Leorio para curar a los demás?",
            "opciones": {"A": "Kairo", "B": "Hatsu de curación", "C": "Sanación Nen"},
            "respuesta": "C"},
            {"pregunta": "¿Quién es el primer mentor de Gon?",
            "opciones": {"A": "Biscuit Krueger", "B": "Hisoka", "C": "Kaito"},
            "respuesta": "C"},
            {"pregunta": "¿Qué técnica utiliza Killua para moverse a alta velocidad?",
            "opciones": {"A": "Gyo", "B": "Ren", "C": "Godspeed"},
            "respuesta": "C"},
            {"pregunta": "¿Quién es el antagonista principal de la saga de las hormigas quimera?",
            "opciones": {"A": "Netero", "B": "Hisoka", "C": "Meruem"},
            "respuesta": "C"}
    ]
}

def obtenerPreguntasHXH():
    return preguntas["Hunter X Hunter"]