preguntas = {
"Pokémon":[
    {"pregunta": "¿Cuál es el Pokémon inicial de tipo fuego en la primera generación?",
    "opciones": {"A": "Charmander", "B": "Cyndaquil", "C": "Torchic"},
    "respuesta": "A"},
    {"pregunta": "¿Qué tipo de Pokémon es Pikachu?",
    "opciones": {"A": "Eléctrico", "B": "Fuego", "C": "Agua"},
    "respuesta": "A"},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Dios Pokémon'?",
    "opciones": {"A": "Arceus", "B": "Mew", "C": "Dialga"},
    "respuesta": "A"},
    {"pregunta": "¿Cuál es el Pokémon legendario de tipo eléctrico de la primera generación?",
    "opciones": {"A": "Zapdos", "B": "Raikou", "C": "Thundurus"},
    "respuesta": "A"},
    {"pregunta": "¿En qué generación se introdujo la región de Hoenn?",
    "opciones": {"A": "Tercera", "B": "Cuarta", "C": "Segunda"},
    "respuesta": "A"},
    {"pregunta": "¿Qué Pokémon es conocido por poder aprender casi cualquier movimiento?",
    "opciones": {"A": "Mew", "B": "Ditto", "C": "Eevee"},
    "respuesta": "A"},
    {"pregunta": "¿Cuál es la evolución final de Charmander?",
    "opciones": {"A": "Charizard", "B": "Charmeleon", "C": "Mega Charizard"},
    "respuesta": "A"},
    {"pregunta": "¿Qué tipo de Pokémon es super efectivo contra los tipo Agua?",
    "opciones": {"A": "Eléctrico", "B": "Planta", "C": "Hielo"},
    "respuesta": "A"},
    {"pregunta": "¿Qué Pokémon tiene como habilidad única 'Trampa Arena'?",
    "opciones": {"A": "Trapinch", "B": "Sandshrew", "C": "Diglett"},
    "respuesta": "A"},
    {"pregunta": "¿Qué objeto se usa para evolucionar a Eevee en Jolteon?",
    "opciones": {"A": "Piedra Trueno", "B": "Piedra Solar", "C": "Piedra Lunar"},
    "respuesta": "A"},
    {"pregunta": "¿Qué Pokémon fue el primer diseño creado por Game Freak?",
    "opciones": {"A": "Rhydon", "B": "Pikachu", "C": "Bulbasaur"},
    "respuesta": "A"},
    {"pregunta": "¿Cuál es el Pokémon inicial de tipo planta en la primera generación?",
    "opciones": {"A": "Bulbasaur", "B": "Chikorita", "C": "Treecko"},
    "respuesta": "A"},
    {"pregunta": "¿Qué región es conocida por tener el Equipo Galaxia?",
    "opciones": {"A": "Sinnoh", "B": "Unova", "C": "Johto"},
    "respuesta": "A"},
    {"pregunta": "¿Qué tipo es débil contra el tipo Dragón?",
    "opciones": {"A": "Dragón", "B": "Hada", "C": "Hielo"},
    "respuesta": "A"},
    {"pregunta": "¿Qué Pokémon aparece en la portada de Pokémon Azul?",
    "opciones": {"A": "Blastoise", "B": "Charizard", "C": "Vaporeon"},
    "respuesta": "A"},
    {"pregunta": "¿Qué tipo de gimnasio lidera Brock?",
    "opciones": {"A": "Roca", "B": "Tierra", "C": "Acero"},
    "respuesta": "A"},
    {"pregunta": "¿Qué Pokémon es conocido por poder transformarse en cualquier otro?",
    "opciones": {"A": "Ditto", "B": "Mew", "C": "Zorua"},
    "respuesta": "A"},
    {"pregunta": "¿En qué generación se introdujeron las batallas dobles?",
    "opciones": {"A": "Tercera", "B": "Segunda", "C": "Cuarta"},
    "respuesta": "A"},
    {"pregunta": "¿Qué objeto necesitas para evolucionar a Poliwhirl en Politoed?",
    "opciones": {"A": "Roca del Rey", "B": "Piedra Agua", "C": "Piedra Lunar"},
    "respuesta": "A"},
    {"pregunta": "¿Qué Pokémon tiene la habilidad 'Corte Fuerte'?",
    "opciones": {"A": "Aegislash", "B": "Honedge", "C": "Scyther"},
    "respuesta": "A"},
    {"pregunta": "¿Qué tipo es efectivo contra Pokémon tipo Psíquico?",
    "opciones": {"A": "Eléctrico", "B": "Siniestro", "C": "Hada"},
    "respuesta": "B"},
    {"pregunta": "¿Cuál es el Pokémon inicial de tipo agua en la segunda generación?",
    "opciones": {"A": "Squirtle", "B": "Totodile", "C": "Mudkip"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Guardián del Mar'?",
    "opciones": {"A": "Kyogre", "B": "Lugia", "C": "Manaphy"},
    "respuesta": "B"},
    {"pregunta": "¿En qué generación se introdujo la Mega Evolución?",
    "opciones": {"A": "Quinta", "B": "Sexta", "C": "Cuarta"},
    "respuesta": "B"},
    {"pregunta": "¿Qué región es conocida por tener el Equipo Plasma?",
    "opciones": {"A": "Johto", "B": "Unova", "C": "Sinnoh"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon inicial tiene la forma evolucionada Infernape?",
    "opciones": {"A": "Torchic", "B": "Chimchar", "C": "Tepig"},
    "respuesta": "B"},
    {"pregunta": "¿Qué tipo de Pokémon es efectivo contra tipo Acero?",
    "opciones": {"A": "Planta", "B": "Fuego", "C": "Eléctrico"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon es conocido como el clon de Mew?",
    "opciones": {"A": "Mewtwo", "B": "Ditto", "C": "Genesect"},
    "respuesta": "A"},
    {"pregunta": "¿Qué objeto se necesita para evolucionar a Eevee en Umbreon?",
    "opciones": {"A": "Piedra Noche", "B": "Amistad de noche", "C": "Piedra Oscura"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon se encuentra en la portada de Pokémon Plata?",
    "opciones": {"A": "Ho-Oh", "B": "Lugia", "C": "Celebi"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon tiene la habilidad única 'Llovizna' en la tercera generación?",
    "opciones": {"A": "Manaphy", "B": "Kyogre", "C": "Pelipper"},
    "respuesta": "B"},
    {"pregunta": "¿Qué tipo es super efectivo contra Pokémon tipo Dragón?",
    "opciones": {"A": "Hielo", "B": "Hada", "C": "Fuego"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Rey del Abismo'?",
    "opciones": {"A": "Lugia", "B": "Kyogre", "C": "Groudon"},
    "respuesta": "B"},
    {"pregunta": "¿Qué región introdujo a los Pokémon de tipo Hada por primera vez?",
    "opciones": {"A": "Unova", "B": "Kalos", "C": "Sinnoh"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon legendario aparece en la portada de Pokémon Y?",
    "opciones": {"A": "Xerneas", "B": "Yveltal", "C": "Zygarde"},
    "respuesta": "B"},
    {"pregunta": "¿Cuál es la evolución final de Piplup?",
    "opciones": {"A": "Prinplup", "B": "Empoleon", "C": "Samurott"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon tiene como habilidad principal 'Intimidación'?",
    "opciones": {"A": "Salamence", "B": "Arcanine", "C": "Luxray"},
    "respuesta": "B"},
    {"pregunta": "¿En qué generación se introdujo a Lucario?",
    "opciones": {"A": "Tercera", "B": "Cuarta", "C": "Quinta"},
    "respuesta": "B"},
    {"pregunta": "¿Qué tipo de Pokémon lidera el gimnasio de Erika?",
    "opciones": {"A": "Agua", "B": "Planta", "C": "Bicho"},
    "respuesta": "B"},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Dragón de la Tierra'?",
    "opciones": {"A": "Groudon", "B": "Tornadus", "C": "Rayquaza"},
    "respuesta": "A"},
    {"pregunta": "¿En qué generación se introdujeron los 'Paseos Pokémon'?",
    "opciones": {"A": "Quinta", "B": "Sexta", "C": "Cuarta"},
    "respuesta": "C"},
    {"pregunta": "¿Qué habilidad tiene el Pokémon Zygarde?",
    "opciones": {"A": "Aura Rápida", "B": "Escudo Místico", "C": "Regeneración"},
    "respuesta": "C"}
    ]
}

def obtenerPreguntasPokemon():
    return preguntas["Pokémon"]