preguntas = {
    "One Piece": [
        {"pregunta": "¿Quién es el capitán de los Piratas del Sombrero de Paja?",
        "opciones": {"A": "Monkey D. Luffy", "B": "Roronoa Zoro", "C": "Nami"},
        "respuesta": "A"},
        {"pregunta": "¿Qué fruta del diablo comió Luffy?",
        "opciones": {"A": "Gomu Gomu no Mi", "B": "Mera Mera no Mi", "C": "Hie Hie no Mi"},
        "respuesta": "A"},
        {"pregunta": "¿Quién es el primer miembro de la tripulación de Luffy?",
        "opciones": {"A": "Roronoa Zoro", "B": "Nami", "C": "Usopp"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llama el hermano de Luffy?",
        "opciones": {"A": "Ace", "B": "Zoro", "C": "Dragon"},
        "respuesta": "A"},
        {"pregunta": "¿Quién es el doctor de los Piratas del Sombrero de Paja?",
        "opciones": {"A": "Tony Tony Chopper", "B": "Nami", "C": "Franky"},
        "respuesta": "A"},
        {"pregunta": "¿Qué significa el apodo de Zoro, 'Marimo'?",
        "opciones": {"A": "Cabeza de alga", "B": "El mejor espadachín", "C": "Capitán"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llama el barco de Luffy?",
        "opciones": {"A": "Going Merry", "B": "Black Pearl", "C": "Queen Anne"},
        "respuesta": "A"},
        {"pregunta": "¿Qué poder tiene la fruta Gomu Gomu no Mi?",
        "opciones": {"A": "Poder de goma", "B": "Poder del fuego", "C": "Poder de control del viento"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llama la hermana de Sanji?",
        "opciones": {"A": "Reiju Vinsmoke", "B": "Nami", "C": "Robin"},
        "respuesta": "A"},
        {"pregunta": "¿En qué isla Luffy y su tripulación luchan contra el Gobierno Mundial?",
        "opciones": {"A": "En Enies Lobby", "B": "En Dressrosa", "C": "En Skypiea"},
        "respuesta": "A"},
        {"pregunta": "¿Quién es el antagonista principal en Arabasta?",
        "opciones": {"A": "Mihawk", "B": "Shanks", "C": "Crocodile"},
        "respuesta": "C"},
        {"pregunta": "¿Cómo se llama el hermano de Sabo?",
        "opciones": {"A": "Edward Newgate", "B": "Ace", "C": "Gol D. Roger"},
        "respuesta": "B"},
        {"pregunta": "¿En qué arco los Piratas del Sombrero de Paja derrotan a Gecko Moria?",
        "opciones": {"A": "En Thriller Bark", "B": "En Marineford", "C": "En Wano"},
        "respuesta": "A"},
        {"pregunta": "¿Cuál es la fruta del diablo de Nico Robin?",
        "opciones": {"A": "Hana Hana no Mi", "B": "Soru Soru no Mi", "C": "Goro Goro no Mi"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llama el abuelo de Luffy?",
        "opciones": {"A": "Monkey D. Garp", "B": "Gol D. Roger", "C": "Dracule Mihawk"},
        "respuesta": "A"},
        {"pregunta": "¿Quién es el capitán de los Piratas de los Corazones?",
        "opciones": {"A": "Trafalgar D. Water Law", "B": "Shanks", "C": "Blackbeard"},
        "respuesta": "A"},
        {"pregunta": "¿Qué habilidad tiene Franky?",
        "opciones": {"A": "Es un cyborg", "B": "Es un espadachín", "C": "Es un navegante"},
        "respuesta": "A"},
        {"pregunta": "¿Cual es el objetivo de Luffy?",
        "opciones": {"A": "Ser el Rey de los Piratas", "B": "Vengar la muerte de su madre", "C": "Encontrar la Ciudad del Sol"},
        "respuesta": "A"},
        {"pregunta": "¿Qué tipo de fruta comió Blackbeard?",
        "opciones": {"A": "Yami Yami no Mi", "B": "Gura Gura no Mi", "C": "Mero Mero no Mi"},
        "respuesta": "A"},
        {"pregunta": "¿Cómo se llama la isla de los gigantes?",
        "opciones": {"A": "Elbaf", "B": "Skypiea", "C": "Water 7"},
        "respuesta": "A"},
        {"pregunta": "¿Quién fue el primer miembro de la tripulación que se unió a Luffy?",
        "opciones": {"A": "Nami", "B": "Zoro", "C": "Sanji"},
        "respuesta": "B"},
        {"pregunta": "¿Cuál es el sueño de Nami?",
        "opciones": {"A": "Ser la mejor espadachina", "B": "Crear un mapa del mundo", "C": "Encontrar el One Piece"},
        "respuesta": "B"},
        {"pregunta": "¿Cómo se llama el padre de Luffy?",
        "opciones": {"A": "Gol D. Roger", "B": "Monkey D. Dragon", "C": "Shanks"},
        "respuesta": "B"},
        {"pregunta": "¿Cómo se llama el lugar donde los Piratas del Sombrero de Paja se reunen tras el timeskip?",
        "opciones": {"A": "Wano", "B": "Sabaody Archipelago", "C": "Ruskaina"},
        "respuesta": "B"},
        {"pregunta": "¿Qué fruta del diablo comió Buggy?",
        "opciones": {"A": "Mera Mera no Mi", "B": "Bara Bara no Mi", "C": "Suna Suna no Mi"},
        "respuesta": "B"},
        {"pregunta": "¿Quién es el líder de los Guerreros de los Hombres Peces?",
        "opciones": {"A": "Fisher Tiger", "B": "Arlong", "C": "Jinbe"},
        "respuesta": "B"},
        {"pregunta": "¿Quién es el navegante de los Piratas del Sombrero de Paja?",
        "opciones": {"A": "Robin", "B": "Nami", "C": "Franky"},
        "respuesta": "B"},
        {"pregunta": "¿Quién es el que posee la Fruta Mero Mero no Mi?",
        "opciones": {"A": "Boa Hancock", "B": "Nico Robin", "C": "Shirley"},
        "respuesta": "A"},
        {"pregunta": "¿Dónde nació Sanji?",
        "opciones": {"A": "En East Blue", "B": "En el Mar del Sur", "C": "En North Blue"},
        "respuesta": "C"},
        {"pregunta": "¿Qué tipo de fruta del diablo comió Ace?",
        "opciones": {"A": "Mera Mera no Mi", "B": "Gomu Gomu no Mi", "C": "Suna Suna no Mi"},
        "respuesta": "A"},
        {"pregunta": "¿Cuál es la fruta del diablo de Luffy?",
        "opciones": {"A": "Mera Mera no Mi", "B": "Gomu Gomu no Mi", "C": "Tori Tori no Mi"},
        "respuesta": "B"},
        {"pregunta": "¿Qué grupo desea conseguir el One Piece?",
        "opciones": {"A": "Los Revolucionarios", "B": "Los Piratas del Sombrero de Paja", "C": "Los Shichibukai"},
        "respuesta": "B"},
        {"pregunta": "¿Quién es el mejor espadachín del mundo?",
        "opciones": {"A": "Roronoa Zoro", "B": "Dracule Mihawk", "C": "Shanks"},
        "respuesta": "B"},
        {"pregunta": "¿Cómo se llama el arco donde se desarrolla la batalla en Dressrosa?",
        "opciones": {"A": "Arco de Punk Hazard", "B": "Arco de Dressrosa", "C": "Arco de Skypiea"},
        "respuesta": "B"},
        {"pregunta": "¿Quién es el dueño del barco Thousand Sunny?",
        "opciones": {"A": "Luffy", "B": "Law", "C": "Big Mom"},
        "respuesta": "A"},
        {"pregunta": "¿Cuál es la habilidad de Sanji?",
        "opciones": {"A": "Uso de pistolas", "B": "Uso de fuego", "C": "Uso de piernas"},
        "respuesta": "C"},
        {"pregunta": "¿Cuál es la habilidad de Nico Robin?",
        "opciones": {"A": "Control del fuego", "B": "Generación de brazos", "C": "Viaje en el tiempo"},
        "respuesta": "B"},
        {"pregunta": "¿Quién es la que posee la Fruta Mero Mero no Mi?",
        "opciones": {"A": "Boa Hancock", "B": "Nico Robin", "C": "Shirley"},
        "respuesta": "A"},
        {"pregunta": "¿Quién es la madre de Luffy?",
        "opciones": {"A": "Nadie sabe", "B": "Basil Hawkins", "C": "No se menciona"},
        "respuesta": "C"}
    ]
}

def obtenerPreguntasOnePiece():
    return preguntas["One Piece"]